import os
from pathlib import Path
from rdflib import Graph, Namespace, URIRef, OWL, RDFS, RDF, Literal
from pyshacl import validate

# 1. Path Setup
BASE_DIR = Path(__file__).resolve().parent
ONTOLOGY_DIR = (BASE_DIR / "../ontology").resolve()

SCHEMA_FILE = ONTOLOGY_DIR / "schema.ttl"
DATA_FILE = ONTOLOGY_DIR / "output_graph.ttl"
SHAPES_FILE = ONTOLOGY_DIR / "shapes.ttl"
OUTPUT_FILE = ONTOLOGY_DIR / "production_graph.ttl"

CINE = Namespace("http://filmgraph/ontology/")

def cleanup_duplicates(graph):
    films = set(graph.subjects(predicate=CINE.releaseYear))
    
    for film in films:
        years = sorted(list(graph.objects(film, CINE.releaseYear)))
        if len(years) > 1:
            print(f"Squashing duplicate years for {film.split('/')[-1]}: kept {years[0]}")
            graph.remove((film, CINE.releaseYear, None))
            graph.add((film, CINE.releaseYear, years[0]))

def run_pipeline():
    print(f"Checking paths in: {ONTOLOGY_DIR}")
    
    if not DATA_FILE.exists():
        print(f"❌ Critical Error: {DATA_FILE.name} not found!")
        return

    data_graph = Graph()
    data_graph.bind("cine", CINE) 
    
    print(f"Loading {DATA_FILE.name}...")
    data_graph.parse(str(DATA_FILE), format="turtle")
    
    if SCHEMA_FILE.exists():
        print(f"Loading {SCHEMA_FILE.name} for reasoning context...")
        data_graph.parse(str(SCHEMA_FILE), format="turtle")

    cleanup_duplicates(data_graph)

    shacl_graph = None
    if SHAPES_FILE.exists():
        print("Loading Validation Shapes...")
        shacl_graph = Graph()
        shacl_graph.parse(str(SHAPES_FILE), format="turtle")

    print("Running Validation and OWLRL Inference...")
    conforms, _, results_text = validate(
        data_graph,
        shacl_graph=shacl_graph,
        inference='owlrl', 
        inplace=True 
    )

    # Remove illegal triples generated by the reasoner
    print("Scrubbing illegal literal-subject triples...")
    bad_triples = 0
    for s, p, o in list(data_graph):
        if isinstance(s, Literal):
            data_graph.remove((s, p, o))
            bad_triples += 1
        if isinstance(p, Literal):
            data_graph.remove((s, p, o))
            bad_triples += 1
    
    if bad_triples > 0:
        print(f"Cleaned up {bad_triples} illegal triples (literal subjects/predicates).")

    print("Final Polish: Removing reasoning noise...")
    
    to_remove = []

    for s, p, o in data_graph:
        # Remove Reflexive Junk (A owl:sameAs A)
        if s == o and p == OWL.sameAs:
            to_remove.append((s, p, o))
        
        # Remove "Self-Starred" noise (Actor coStarredWith Actor, etc.)
        if s == o and p == CINE.coStarredWith:
            to_remove.append((s, p, o))

        if s == o and p == CINE.coDirectedWith:
            to_remove.append((s, p, o))

        if s == o and p == CINE.workedWith:
            to_remove.append((s, p, o))
        
        if o == OWL.Thing:
            types = list(data_graph.objects(s, RDF.type))
            if len(types) > 1:
                to_remove.append((s, p, o))

    for triple in to_remove:
        data_graph.remove(triple)

    turtle_output = data_graph.serialize(format="turtle")

    # Binary Write to File
    print(f"Saving cleaned graph to {OUTPUT_FILE}...")
    with open(OUTPUT_FILE, "wb") as f:
        f.write(turtle_output.encode("utf-8"))
    
    print(f"✅ Final Graph Size: {len(data_graph)} triples.")

if __name__ == "__main__":
    run_pipeline()